### ISSUE TITLE
User is returned to Landing Page when refreshing browser

### ISSUE THREAD

**Issue by nikhilkamineni** [Lambda-School-Labs/Labs_7_1_Map#46]
Currently when you are signed in and you refresh the browser, you are returned to the Landing Page and have to sign in again.

Need to have it so the browser detects if the user is already signed in (has a valid token etc.) and send back the relevant user data back to be rendered in the client.

**Comment by Davidless** [comment]
Was this fixed?

**Comment by nikhilkamineni** [comment]
Yep.
